pipeline {
    agent any

    stages {
        stage('Checkout') { // Stage 1: Pull latest code from Git
            steps {
                git branch: 'dev', url: 'https://github.com/saakanbi/NumberGuessGame.git' // Replace with your repository URL
            }
        }

        stage('Build') { // Stage 2: Build the application
            steps {
                script {
                    sh 'mvn clean package' // Replace with your build command (e.g., npm install, build tool)
                }
            }
        }

        stage('Test') { // Stage 3: Run tests
            steps {
                sh 'mvn test' // Replace with your test command (e.g., npm test)
            }
        }

        stage('Deploy') { // Stage 4: Deploy the application
            steps {
                echo 'Deploying'// Replace with your deployment command
            }
        }
    }

    post { // The post block should be inside the pipeline block, after the stages
        success {
            echo 'Build and Deployment Successful'
            // Optional: Send notifications or alerts here
        }
        failure {
            echo 'Build or Deployment failed'
            // Optional: Send failure notifications or alerts here
        }

        always {
            // Archive the WAR file as an artifact for later inspection
            archiveArtifacts artifacts: 'target/*.war', allowEmptyArchive: true
            // Archive test results if they are generated by your testing framework
            junit '**/target/test-*.xml' // Replace with the location of your test results
        }
    }
}

